### ISSUE TITLE
TASK: Write javascript code to validate the data being entered.

### ISSUE THREAD

**Issue by snmackay** [snmackay/CSE-442#15]
ASSOCIATED USER STORY: #1
ASSOCIATED BRANCH: emailFilter_dev

**Comment by brconomo** [comment]
Tests
Enter any random text that does not match a buffalo.edu email format into the email textbox on the login page.
Make sure that the form will not submit with said text.

Random text tried: 
1: typing @gmail.com before @buffalo.edu
2: Just @buffalo.edu
3: other types of emails
4: text after @buffalo.edu

NOTE: Was addressed in 71084d0 using HTML5 instead of JS. HTML5 had the required features to do this.
